In [16]:
import numpy as np


# 1. Create a null vector of size 10 but the fifth value which is 1.

In [18]:
x=np.zeros(10)
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# 2. Create a vector with values ranging from 10 to 49.

In [30]:
x = np.arange(10,50)
print("vector with values ranging:")
print(x)


vector with values ranging:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# 3. Create a 3x3 matrix with values ranging from 0 to 8

In [28]:
x =  np.arange(0,9)
x = x.reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [35]:
x = [1,2,0,0,4,0]
np.nonzero(x)

(array([0, 1, 4], dtype=int64),)

# 5. Create a 10x10 array with random values and find the minimum and maximum values.

In [42]:
x = np.random.random((10,10))
print("The 10*10 array with random values :")
print(x)
print("The minimum values in the array :",x.min())
print("The maximum values in the array :",x.max())

The 10*10 array with random values :
[[0.85355031 0.64953443 0.33882039 0.75475696 0.14819266 0.14246512
  0.71911226 0.18213469 0.10492181 0.2563258 ]
 [0.13271461 0.09558571 0.95797229 0.02705183 0.4605604  0.8119543
  0.58986144 0.54405574 0.02782191 0.50232367]
 [0.77743802 0.63438179 0.03962486 0.24030496 0.71959748 0.72477182
  0.35468062 0.99999901 0.11912989 0.56932092]
 [0.3498986  0.34419954 0.5750434  0.76189959 0.3773373  0.05688865
  0.18029478 0.34802229 0.7961622  0.25772203]
 [0.41168757 0.06026551 0.10773755 0.80920129 0.94978004 0.18799551
  0.07181165 0.10882279 0.60645403 0.92321627]
 [0.14310245 0.21640601 0.97461614 0.2068915  0.14931591 0.98623073
  0.39360027 0.58414332 0.03984223 0.18064111]
 [0.41682209 0.72072731 0.01601676 0.02158235 0.87967935 0.11767434
  0.25779598 0.1152266  0.71063606 0.77440613]
 [0.07669431 0.13257913 0.50680032 0.94105881 0.70480366 0.82810468
  0.38741389 0.3493509  0.05596111 0.88438853]
 [0.74993094 0.1209653  0.90011715 0.5285527

# 6. Create a random vector of size 30 and find the mean value.

In [46]:
x = np.random.random(30)
print("Random vector of size 30 array:")
print(x)
print("The mean of the array is :",x.mean())

Random vector of size 30 array:
[0.1748892  0.78615934 0.08407541 0.92551247 0.15343194 0.28745892
 0.96158142 0.10283924 0.97854305 0.04451657 0.62405274 0.81074344
 0.89470262 0.54730289 0.17164693 0.54369837 0.97641619 0.48120749
 0.61171908 0.35300467 0.04374628 0.67871178 0.37951351 0.41304608
 0.09551292 0.57998549 0.00945951 0.56930384 0.03656982 0.94414575]
The mean of the array is : 0.47544989896343154
